name: Setup repository
on:
  workflow_dispatch:
  push:
      branches: [main]
jobs:
  setup:
    name: Initialise OpenSAFELY project fork.
    runs-on: ubuntu-latest
    steps:
      - name: Do not run on template repository
        shell: bash
        # The only way to trigger this to run when cloned is on push to main.
        # But that means it would also trigger when we push to the template
        # repo itself, which we do not want. So, exit early if we are running
        # on template repo.
        run: |
          curl --silent -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.baptiste-preview+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq --exit-status '.is_template == false';

      - uses: actions/checkout@v2
      - name: Update README.md
        shell: bash
        run: |
          export GITHUB_REPOSITORY_OWNER="$(echo $GITHUB_REPOSITORY | awk -F/ '{print $1}')"
          export GITHUB_REPOSITORY_NAME="$(echo $GITHUB_REPOSITORY | awk -F/ '{print $2}')"
          envsubst < README.md > tmp && mv tmp README.md
      - name: Remove setup workflow
        run: rm .github/workflows/setup.yaml
      - name:
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit --amend --no-edit
          git push origin main --force-with-lease
