name: Setup repository
on:
  fork:
jobs:
  setup:
    name: Initialise OpenSAFELY project fork.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README.md
        shell: bash
        run: |
          export GITHUB_REPOSITORY_OWNER="$(echo $GITHUB_REPOSITORY | awk -F/ '{print $1}')"
          export GITHUB_REPOSITORY_NAME="$(echo $GITHUB_REPOSITORY | awk -F/ '{print $2}')"
          envsubst < README.md > tmp && mv tmp README.md
      - name: Remove setup workflow
        run: rm .github/workflows/setup.yaml
      - name:
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m 'Setup repository'
          git push origin main --force-with-lease
