name: Setup repository
on:
  workflow_dispatch:
  push:
      branches: [main]
jobs:
  setup:
    name: Initialise OpenSAFELY project.
    runs-on: ubuntu-latest
    steps:
      - name: Do not run on template repository
        id: is_template
        shell: bash
        # The only way to trigger this to run when cloned is on push to main.
        # But that means it would also trigger when we push to the template
        # repo itself, which we do not want. So, exit early if we are running
        # on template repo.
        run: |
          # check if this is a template repo
          is_template=false
          curl --silent -X GET \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.baptiste-preview+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY \
            | jq --exit-status '.is_template == false' || is_template=true
          # output true/false so later actions can be skipped
          echo "::set-output name=is_template::$is_template"

      - uses: actions/checkout@v2
        if: steps.is_template.outputs.is_template == 'false'
      - name: Update README.md
        if: steps.is_template.outputs.is_template == 'false'
        shell: bash
        run: |
          export GITHUB_REPOSITORY_OWNER="$(echo $GITHUB_REPOSITORY | awk -F/ '{print $1}')"
          export GITHUB_REPOSITORY_NAME="$(echo $GITHUB_REPOSITORY | awk -F/ '{print $2}')"
          envsubst < README.md > tmp && mv tmp README.md
      - name: Remove setup workflow
        if: steps.is_template.outputs.is_template == 'false'
        run: rm .github/workflows/setup.yaml
      - name: Commit changes
        if: steps.is_template.outputs.is_template == 'false'
        run: |
          # use the same author as the initial commit
          git config user.email "$(git log -1 --pretty=format:'%ae')"
          git config user.name "$(git log -1 --pretty=format:'%an')"
          git add .
          git commit --amend --no-edit
          git push origin main --force
